# Add Repository
tap 'homebrew/versions'
tap 'caskroom/versions'
# tap 'homebrew/binary'
tap 'homebrew/dupes'
tap 'homebrew/apache'
tap 'homebrew/science'
tap 'homebrew/php'
tap 'tldr-pages/tldr'

# For cask
tap 'phinze/homebrew-cask'
brew 'brew-cask'

# Formula
brew 'zsh'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'git'
brew 'readline'
brew 'httpd24'
brew 'mysql'
brew 'tree'
brew 'libjpeg'
brew 'libpng'
brew 'libmcrypt'
brew 'redis'
brew 'opencv'
brew 'imagemagick'
brew 'lua'
brew 'mercurial'
brew 'r'
brew 'composer'
brew 'jq'
brew 'mecab'
brew 'mecab-ipadic'
brew 'cabocha'
brew 'nkf'
brew 'git-flow'
brew 'rename'
brew 'tldr'

# .dmg apps
cask 'alfred'
cask 'bettertouchtool'
cask 'dash'
cask 'dropbox'
cask 'evernote'
cask 'firefox-ja'
cask 'gimp'
cask 'google-chrome'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'haroopad'
cask 'iterm2'
cask 'karabiner'
cask 'mactex'
cask 'mysqlworkbench'
cask 'rstudio'
cask 'skype'
cask 'slack'
cask 'sourcetree'
cask 'thunderbird-ja'
cask 'visual-studio-code'
cask 'xquartz'
cask 'xtrafinder'
