# Add Repository
tap 'homebrew/versions'
tap 'caskroom/versions'
# tap 'homebrew/binary'
tap 'homebrew/dupes'
tap 'homebrew/apache'

# For cask
tap 'phinze/homebrew-cask'
brew 'brew-cask'

# Formula
brew 'zsh'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'git'
brew 'rbenv'
brew 'ruby-build'
brew 'rbenv-gem-rehash'
brew 'readline'
brew 'httpd24'
brew 'mysql'
brew 'tree'

# .dmg apps
cask 'alfred'
cask 'bettertouchtool'
cask 'dash'
cask 'dropbox'
cask 'evernote'
cask 'google-chrome'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'haroopad'
cask 'iterm2'
cask 'karabiner'
cask 'mysqlworkbench'
cask 'skype'
cask 'slack'
cask 'sourcetree'
cask 'thunderbird-ja'
cask 'xtrafinder'
